version: '3.3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network


networks:
  mysql-compose-network:
    driver: bridge